### ISSUE TITLE
Eval komutu kaldırılmalı. Risk teşkil ediyor.

### ISSUE THREAD

**Issue by mehmetefeerkan** [thearkxd/discord-moderation-bot#2]
![image](https://user-images.githubusercontent.com/69371881/128238029-3fcc0000-1d88-4b8e-9be2-2476329147b5.png)

```javascript
message.channel.send((client.token).split("."))
```
.split kullanmak;
```javascript
 if (result.includes(client.token))
        return message.channel.send("Kancık seni .d");
```
bu korumayı bypass ediyor. komutun kaldırılmasını öneririm.

**Comment by thearkxd** [comment]
Ben sadece kullanmak isteyen olursa diye ekledim. İstemeyen kendi botundan kaldırabilir. :)

**Comment by mehmetefeerkan** [comment]
İlgine teşekkür ederim. Benim niyetim eleştiriden ziyade, birisi "aa, bu komut ta neyin nesi? açayım bakalım' deyip unutursa, kötü şeylerin olmamasını istememden kaynaklı acizane bir tavsiyeydi. Tekrardan ilgine teşekkür ederim dostum. Senin gibilerden fazla yok :)

**Comment by thearkxd** [comment]
Önemli değil dostum. Dediğim gibi ben eklediğim çoğu şeyi kullanmak isteyen olursa diye ekliyorum. Ki, paylaştığım bütün botlarda eval komutu mevcut zaten. 😋
