### ISSUE TITLE
help asap

### ISSUE THREAD

**Issue by python-hmv** [thearkxd/discord-moderation-bot#3]
node:internal/modules/cjs/loader:1170
    throw err;
    ^

SyntaxError: /home/container/src/config.json: Unexpected token : in JSON at position 15
    at parse (<anonymous>)

**Comment by Iucious** [comment]
fix ur token

**Comment by Iucious** [comment]
make sure its a bot token not a user token

**Comment by muratvastark** [comment]
misconfiguration
